### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by lurregolab** [Brian-Williams/robotframework-testlink#1]
Hello, when I run the example it generates an error:  Taking listener 'reportlink:testplanname=Automatización_Pymes:buildname=Pymes_MV1' into use failed: Importing listener 'reportlink' failed: ModuleNotFoundError: No module named 'reportlink'
Traceback (most recent call last):

:(

**Comment by Brian-Williams** [comment]
Please see https://github.com/Brian-Williams/robotframework-testlink/issues/2
