### ISSUE TITLE
[ ERROR ] Taking listener 'reportestlink.py:testplanname=Example1:testlinkbuildname=1' into use failed: Importing listener 'reportestlink.py' failed: ModuleNotFoundError: No module named 'reportestlink'

### ISSUE THREAD

**Issue by lurregolab** [Brian-Williams/robotframework-testlink#2]
[ ERROR ] Taking listener 'reportestlink.py:testplanname=Example1:testlinkbuildname=1' into use failed: Importing listener 'reportestlink.py' failed: ModuleNotFoundError: No module named 'reportestlink'

**Comment by Brian-Williams** [comment]
Did you install the module? `pip install robottestlink`
